name: Rust coverage

on:
  push:
    paths:
      - 'src/*'

    branchs:
      - master
  
  pull_request:
    types: ["opened", "ready_for_review", "review_requested"]
    paths:
      - 'src/*'

jobs:
  coverage:

    runs-on: ubuntu-latest

    container:
      image: enderevents/grcov
      env:
        PROJECT_NAME: red_black_tree

    steps:
    - uses: actions/checkout@v1
    - name: Generate lcov
      run: |
        mkdir -p /output
        /coverage.sh
    - name: Upload lcov to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        curl -s https://codecov.io/bash > codecov.sh
        chmod +x codecov.sh
        ./codecov.sh -f /output/lcov.info
