name: Rust test

on:
  push:
    paths:
      - 'src/*'
      - '.github/workflows/rust.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
